### ISSUE TITLE
IDE integration

### ISSUE THREAD

**Issue by blokezero** [drupol/drupal-conventions#2]
Hi, I'd like to use your php.cs coding standards in vim (it's the lowercase constants thing!) - is there a way I can alias a `.php_cs.dist` in project root or something?

**Comment by drupol** [comment]
Hello!
Thanks for using the project, it's nice to see !
I will think about using a `.php_cs.dist` and provide feedback here very soon.
Do you have already an idea in your mind to do so ?

**Comment by blokezero** [comment]
I put together a working `.php_cs.dist` but was fustrated by the lower case constants instance.  I just spent a few months programming React and using Prettier and it transformed my workflow never having to format code - but those JS guys are much less prescriptive with their standards - they let you have whatever standard you want!  Which only makes sense when you're working with Drupal coding standards.

I could duplicate the effect by writing something in Vim script to run your script - but I thought I'd check the options before dusting off my limited vim script skills!

Thank you for the project - I have been looking for a simple way to add CS checks to a Drupal project since I stopped using BLT.

**Comment by drupol** [comment]
So if I understand correctly, you're trying to find an easy way to use my project but you'd like to modify the default rules a bit through `.php_cs.dist` ?
Right ?

**Comment by drupol** [comment]
@blokezero ?

**Comment by blokezero** [comment]
Ah, sorry. No - what I'd like to do is use your altered version of PHP CS Fixer to perform automatic code re-formatting within Vim to Drupal coding standards.

I was getting close before using your project by editing `.php_cs.dist` but was blocked by the lowercase constants rule.  What I'd like is to be able to access your version of the PHP CS Fixer script and then point my Vim script at that.  I'll try installing it globally tomorrow and see if I can access it that way.

**Comment by drupol** [comment]
Have you tried to create a file: `.php_cs.dist` that contains:

```php
<?php

return \drupol\DrupalConventions\PhpCsFixer\Config\Drupal7::create();
```

**Comment by blokezero** [comment]
I think that is the right approach but I'm getting class not found - `drupol` not in my composer autoload

**Comment by drupol** [comment]
Have you tried to include the autoload.php file ?


```php
<?php

include 'vendor/autoload.php';

return \drupol\DrupalConventions\PhpCsFixer\Config\Drupal7::create();
```

**Comment by blokezero** [comment]
Awesome - that is so obvious it hurts!  Thank you!  This is what I ended up with:
```
<?php
include 'vendor/autoload.php';
$fixer = \drupol\DrupalConventions\PhpCsFixer\Config\Drupal8::create();
$fixer->setRiskyAllowed(true);
return $fixer;
```

**Comment by drupol** [comment]
Ah nice :-)
However, I'm wondering why you have to do that.

**Comment by blokezero** [comment]
Set risky or the autoload?  Probably the answer to both is that vim is running the PhpCsFixer script from the global installation. I was getting an error back from PhpCsFixer indicating it needed the risky flag set to yes flag to run some rules.

I can't tell you how nice it is to see the formatting get fixed at a key stroke after pulling collegues `-n` commits! Thanks again!

**Comment by drupol** [comment]
The risky stuff. Because it seems that it is something that I have to fix in this package.

What rules are causing the issue ?

I checked the custom rules that I used and none of them are declared as risky. It's weird.

**Comment by blokezero** [comment]
This is what I get without it:
```
Paths from configuration file have been overridden by paths provided as command arguments.

In ConfigurationResolver.php line 344:

  The rules contain risky fixers (declare_strict_types, is_null, strict_compa
  rison, strict_param), but they are not allowed to run. Perhaps you forget t
  o use --allow-risky=yes option?

```

**Comment by drupol** [comment]
Ooooh interesting !

I just pushed a commit to fix it, could you quickly test the dev version ?

If it works, I'll tag a new release asap.

Thanks!

**Comment by blokezero** [comment]
https://github.com/drupol/drupal-conventions/commit/d98b105cc79fcb6d03fae500480ad4f05bcc02ec ?  Works!

**Comment by drupol** [comment]
Great, going to tag release now ;-)

Thanks !!!

**Comment by drupol** [comment]
Tag 1.4.8 now available ;-)

**Comment by drupol** [comment]
Tag 1.4.8 now available ;-)

**Comment by blokezero** [comment]
Great - thank you!
